# Generated by Django 5.0.6 on 2024-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peladas_bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('campo', models.CharField(max_length=100)),
                ('preco', models.FloatField(max_length=100)),
                ('dia', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='', max_length=100)),
                ('hora', models.TimeField()),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('regra', models.CharField(max_length=1000)),
            ],
        ),
    ]
