# Generated by Django 5.0.6 on 2024-06-12 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpelada', '0003_peladas_bd_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='peladas_bd',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsuarioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(choices=[('Atacante', 'Atacante'), ('Defensor', 'Defensor'), ('Goleiro', 'Goleiro'), ('Atacante ou defensor', 'Atacante ou defensor'), ('Atacante ou goleiro', 'Atacante ou goleiro'), ('Goleiro ou defensor', 'Goleiro ou defensor'), ('Qualquer posição', 'Qualquer posição')], default='', max_length=100)),
                ('sobre', models.CharField(max_length=1000)),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
