# Generated by Django 5.0.6 on 2024-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpelada', '0004_alter_peladas_bd_usuario_usuarioinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinfo',
            name='imagem',
            field=models.ImageField(default=1, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
