# Generated by Django 5.0.6 on 2024-06-14 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpelada', '0005_usuarioinfo_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='peladas_bd',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarioinfo',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListaDeJogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dono', to='Qpelada.peladas_bd')),
                ('jogador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
