# Generated by Django 5.0.6 on 2024-06-14 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpelada', '0006_alter_peladas_bd_usuario_alter_usuarioinfo_pessoa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listadejogadores',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listadejogadores',
            name='jogador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
