# Generated by Django 5.0.6 on 2024-06-15 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpelada', '0007_listadejogadores_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrofeusBd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trofeus', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='', max_length=100)),
                ('eleitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleitor', to=settings.AUTH_USER_MODEL)),
                ('pelada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelada', to='Qpelada.peladas_bd')),
            ],
        ),
    ]
