# Generated by Django 5.0.6 on 2024-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpelada', '0008_trofeusbd'),
    ]

    operations = [
        migrations.AddField(
            model_name='peladas_bd',
            name='nota',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trofeusbd',
            name='trofeus',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=100),
        ),
    ]
